# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.enabled", false);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.dom.window.dump.enabled", true);
user_pref("browser.migration.version", 6);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.0.gethashURL", "http://localhost/safebrowsing-dummy/gethash");
user_pref("browser.safebrowsing.provider.0.keyURL", "http://localhost/safebrowsing-dummy/newkey");
user_pref("browser.safebrowsing.provider.0.updateURL", "http://localhost/safebrowsing-dummy/update");
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage", "about:blank");
user_pref("browser.startup.homepage_override.buildID", "20120905151427");
user_pref("browser.startup.homepage_override.mstone", "15.0.1");
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.warnOnQuit", false);
user_pref("devtools.errorconsole.enabled", true);
user_pref("devtools.hud.height", 307);
user_pref("devtools.webconsole.filter.csserror", false);
user_pref("devtools.webconsole.filter.cssparser", false);
user_pref("devtools.webconsole.filter.error", false);
user_pref("devtools.webconsole.filter.exception", false);
user_pref("devtools.webconsole.filter.info", false);
user_pref("devtools.webconsole.filter.jswarn", false);
user_pref("devtools.webconsole.filter.log", false);
user_pref("devtools.webconsole.filter.network", false);
user_pref("devtools.webconsole.filter.networkinfo", false);
user_pref("devtools.webconsole.filter.warn", false);
user_pref("extensions.autoDisableScopes", 10);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.blocklist.url", "http://localhost/extensions-dummy/blocklistURL");
user_pref("extensions.bootstrappedAddons", "{\"jid1-ArbH6YvnfHd8Vw@jetpack\":{\"version\":\"0.1\",\"type\":\"extension\",\"descriptor\":\"/Users/watinha/workspace/aria-check/dev_profile/extensions/jid1-ArbH6YvnfHd8Vw@jetpack.xpi\"}}");
user_pref("extensions.checkCompatibility.15.0", false);
user_pref("extensions.checkCompatibility.nightly", false);
user_pref("extensions.databaseSchema", 13);
user_pref("extensions.enabledAddons", "{972ce4c6-7e08-4474-a285-3208198ce6fd}:15.0.1");
user_pref("extensions.enabledScopes", 5);
user_pref("extensions.getAddons.cache.enabled", false);
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/Applications/Firefox.app/Contents/MacOS/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1347499507000}}},{\"name\":\"app-profile\",\"addons\":{\"jid1-ArbH6YvnfHd8Vw@jetpack\":{\"descriptor\":\"/Users/watinha/workspace/aria-check/dev_profile/extensions/jid1-ArbH6YvnfHd8Vw@jetpack.xpi\",\"mtime\":1349232111000}}}]");
user_pref("extensions.installDistroAddons", false);
user_pref("extensions.lastAppVersion", "15.0.1");
user_pref("extensions.lastPlatformVersion", "15.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.testpilot.runStudies", false);
user_pref("extensions.update.enabled", false);
user_pref("extensions.update.notifyUser", false);
user_pref("extensions.update.url", "http://localhost/extensions-dummy/updateURL");
user_pref("extensions.webservice.discoverURL", "http://localhost/extensions-dummy/discoveryURL");
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("javascript.options.strict", true);
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("startup.homepage_welcome_url", "about:blank");
user_pref("toolkit.startup.last_success", 1349232111);
user_pref("toolkit.telemetry.prompted", 2);
user_pref("urlclassifier.keyupdatetime.http://localhost/safebrowsing-dummy/newkey", 1351824084);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1351820718);
user_pref("urlclassifier.updateinterval", 172800);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
